import { StyleSheet, Dimensions } from 'react-native';

export const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#FFF' },
  flex1: { flex: 1 },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  appHeader: { padding: 15, borderBottomWidth: 1, borderColor: '#EEE' },
  headerTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  logoImage: { width: 140, height: 60 },
  proBadgeHeader: { backgroundColor: '#4CAF50', padding: 8, paddingHorizontal: 15, borderRadius: 20 },
  proText: { color: '#FFF', fontSize: 11, fontWeight: 'bold' },
  searchContainer: { flexDirection: 'row', alignItems: 'center' },
  searchInputMain: { flex: 1, height: 45, backgroundColor: '#F2F2F2', borderRadius: 12, paddingHorizontal: 15, color: '#000' },
  filterToggleBtn: { marginLeft: 10, width: 45, height: 45, backgroundColor: '#F2F2F2', borderRadius: 12, justifyContent: 'center', alignItems: 'center' },
  modeSwitcher: { flexDirection: 'row', marginTop: 15, backgroundColor: '#F2F2F2', borderRadius: 10, padding: 4 },
  modeBtn: { flex: 1, paddingVertical: 8, alignItems: 'center', borderRadius: 8 },
  modeBtnActive: { backgroundColor: '#FFF', shadowColor: '#000', shadowOffset: {width: 0, height: 2}, shadowOpacity: 0.1, shadowRadius: 4, elevation: 2 },
  modeBtnText: { fontSize: 10, fontWeight: 'bold', color: '#888' },
  modeBtnTextActive: { color: '#4CAF50' },
  listPadding: { padding: 5 },
  card: { width: (width / 2) - 15, height: 260, margin: 7, borderRadius: 18, overflow: 'hidden', backgroundColor: '#F9F9F9', elevation: 3 },
  cardImg: { width: '100%', height: '100%' },
  cardOverlay: { position: 'absolute', bottom: 0, left: 0, right: 0, padding: 12, backgroundColor: 'rgba(0,0,0,0.5)' },
  cardNameText: { color: '#FFF', fontWeight: 'bold', fontSize: 16 },
  cardTownText: { color: '#DDD', fontSize: 11 },
  likeBtnSmall: { position: 'absolute', top: 10, right: 10, backgroundColor: 'rgba(255,255,255,0.9)', borderRadius: 20, padding: 6 },
  paginationRow: { height: 70, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, borderTopWidth: 1, borderColor: '#EEE' },
  pageBtn: { backgroundColor: '#4CAF50', padding: 10, borderRadius: 8, minWidth: 80, alignItems: 'center' },
  btnText: { color: '#FFF', fontWeight: 'bold' },
  navBar: { height: 80, flexDirection: 'row', borderTopWidth: 1, borderColor: '#EEE', backgroundColor: '#FFF', paddingBottom: 10 },
  navBtn: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  navItem: { fontSize: 10, fontWeight: 'bold', color: '#999', marginTop: 4 },
  sectionTitle: { fontSize: 24, fontWeight: 'bold', padding: 15, color: '#333' },
  lobbyMsg: { padding: 15, borderBottomWidth: 1, borderColor: '#F5F5F5' },
  lobbyUser: { color: '#4CAF50', fontWeight: 'bold', fontSize: 14 },
  lobbyTime: { color: '#AAA', fontSize: 10 },
  lobbyText: { marginTop: 4, color: '#444', fontSize: 15 },
  adminHeader: { padding: 10, backgroundColor: '#F9F9F9', borderBottomWidth: 1, borderColor: '#EEE' },
  adminInput: { height: 45, backgroundColor: '#FFF', borderRadius: 10, paddingHorizontal: 15, borderWidth: 1, borderColor: '#DDD', marginHorizontal: 15, marginBottom: 10, color: '#000' },
  adminRow: { flexDirection: 'row', padding: 15, borderBottomWidth: 1, borderColor: '#EEE', alignItems: 'center' },
  adminAvatar: { width: 45, height: 45, borderRadius: 22.5, marginRight: 15 },
  adminStatsRow: { flexDirection: 'row', padding: 15, justifyContent: 'space-around' },
  statBox: { alignItems: 'center' },
  statNum: { fontSize: 20, fontWeight: 'bold', color: '#4CAF50' },
  statLab: { fontSize: 12, color: '#999' },
  banBtn: { paddingVertical: 8, paddingHorizontal: 15, borderRadius: 8 },
  btnTextSmall: { color: '#FFF', fontSize: 12, fontWeight: 'bold' },
  darkText: { color: '#333', fontWeight: 'bold', fontSize: 16 },
  padding20: { padding: 20 },
  switchRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginVertical: 15, paddingBottom: 15, borderBottomWidth: 1, borderColor: '#F5F5F5' },
  chatBtn: { backgroundColor: '#4CAF50', padding: 18, borderRadius: 150, alignItems: 'center', margin: 15 },
  swipeContainer: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  swipeCard: { position: 'absolute', width: width * 0.9, height: height * 0.6, borderRadius: 20, overflow: 'hidden', backgroundColor: '#FFF', elevation: 5 },
  swipeImg: { width: '100%', height: '80%' },
  swipeInfo: { padding: 15 },
  swipeName: { fontSize: 22, fontWeight: 'bold' },
  swipeSub: { fontSize: 14, color: '#666' },
  swipeButtons: { flexDirection: 'row', position: 'absolute', bottom: 30 },
  circleBtnRed: { width: 70, height: 70, borderRadius: 35, backgroundColor: '#FFF', justifyContent: 'center', alignItems: 'center', marginRight: 20, elevation: 5 },
  circleBtnGreen: { width: 70, height: 70, borderRadius: 35, backgroundColor: '#FFF', justifyContent: 'center', alignItems: 'center', marginLeft: 20, elevation: 5 },
  radarContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#F9F9F9' },
  radarRing: { position: 'absolute', width: 100, height: 100, borderRadius: 50, borderWidth: 2, borderColor: '#4CAF50' },
  myLocationDot: { width: 15, height: 15, borderRadius: 7.5, backgroundColor: '#4CAF50', elevation: 5 },
  radarUser: { position: 'absolute', alignItems: 'center' },
  radarAvatar: { width: 50, height: 50, borderRadius: 25, borderWidth: 2, borderColor: '#FFF' },
  radarDist: { fontSize: 10, color: '#666', fontWeight: 'bold' },
  radarScanText: { position: 'absolute', bottom: 50, color: '#888', fontWeight: 'bold' },
  inputArea: { flexDirection: 'row', padding: 15, marginBottom: 80, borderTopWidth: 1, borderColor: '#EEE' },
  input: { flex: 1, height: 45, backgroundColor: '#F5F5F5', borderRadius: 20, paddingHorizontal: 15 },
  sendBtn: { marginLeft: 10, backgroundColor: '#4CAF50', paddingHorizontal: 20, borderRadius: 20, justifyContent: 'center' },
  label: { fontSize: 12, color: '#999', marginHorizontal: 15, marginTop: 10, marginBottom: 5 },
  settingsProfileHeader: { alignItems: 'center', marginBottom: 30 },
  settingsAvatar: { width: 120, height: 120, borderRadius: 60, marginBottom: 10 },
  changeImageText: { color: '#4CAF50', fontWeight: 'bold', marginTop: 10, fontSize: 16 },
  detailName: { fontSize: 28, fontWeight: 'bold' },
  detailTown: { fontSize: 16, color: '#666', marginTop: 5 },
  empty: { textAlign: 'center', marginTop: 50, color: '#999' },
  
  // New Styles for Edit Profile Form
  textArea: { height: 100, backgroundColor: '#FFF', borderRadius: 10, padding: 15, borderWidth: 1, borderColor: '#DDD', marginHorizontal: 15, marginBottom: 10, textAlignVertical: 'top', color: '#000' },
  pickerBtn: { height: 45, backgroundColor: '#FFF', borderRadius: 10, paddingHorizontal: 15, borderWidth: 1, borderColor: '#DDD', marginHorizontal: 15, marginBottom: 10, justifyContent: 'center' },
  pickerBtnText: { color: '#333', fontSize: 14 },
  pickerModalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end' },
  pickerModalContainer: { backgroundColor: '#FFF', borderTopLeftRadius: 20, borderTopRightRadius: 20, maxHeight: height * 0.5 },
  pickerModalHeader: { flexDirection: 'row', justifyContent: 'space-between', padding: 20, borderBottomWidth: 1, borderColor: '#EEE', alignItems: 'center' },
  pickerModalTitle: { fontSize: 18, fontWeight: 'bold', color: '#333' },
  pickerModalItem: { padding: 18, borderBottomWidth: 1, borderColor: '#EEE' },
  pickerModalItemText: { fontSize: 16, textAlign: 'center', color: '#000' },

  // Modal Specific
  modalBlur: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  filterSheet: { backgroundColor: '#FFF', borderTopLeftRadius: 30, borderTopRightRadius: 30, padding: 25 },
  sheetHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
  sheetTitle: { fontSize: 20, fontWeight: 'bold' },
  filterLabel: { fontSize: 16, fontWeight: 'bold', marginTop: 15, marginBottom: 10 },
  filterRow: { flexDirection: 'row', marginBottom: 10 },
  filterChip: { paddingVertical: 10, paddingHorizontal: 20, borderRadius: 20, backgroundColor: '#F5F5F5', marginRight: 10 },
  activeChip: { backgroundColor: '#4CAF50' },
  whiteText: { color: '#FFF', fontWeight: 'bold' },
  darkTextSmall: { color: '#333', fontWeight: 'bold' },
  applyBtn: { backgroundColor: '#4CAF50', padding: 15, borderRadius: 15, alignItems: 'center', marginTop: 30 },
  modalHeader: { padding: 15, borderBottomWidth: 1, borderColor: '#EEE' },
  backBtn: { padding: 10 },
  backText: { color: '#4CAF50', fontWeight: 'bold' },
  detailImg: { width: '100%', height: height * 0.5 },
  detailContent: { padding: 20 },
  detailBio: { fontSize: 16, color: '#444', marginTop: 15, lineHeight: 24 },
  profileFavsContainer: { marginTop: 30 },
  favSectionTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 15 },
  miniFavItem: { marginRight: 15, alignItems: 'center' },
  miniFavCircle: { width: 60, height: 60, borderRadius: 30 },
  miniFavName: { fontSize: 10, marginTop: 5, color: '#666' },
  chatHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 40, borderBottomWidth: 1, borderColor: '#EEE' },
  chatTitle: { fontSize: 18, fontWeight: 'bold' },
  chatAvatarSmall: { width: 40, height: 40, borderRadius: 20 },
  bubble: { padding: 12, borderRadius: 20, maxWidth: '80%', marginVertical: 5 },
  myBubble: { alignSelf: 'flex-end', backgroundColor: '#4CAF50' },
  theirBubble: { alignSelf: 'flex-start', backgroundColor: '#F0F0F0' },
  paywallSafe: { flex: 1, backgroundColor: '#FFF' },
  paywallContent: { padding: 20, alignItems: 'center' },
  closePaywall: { alignSelf: 'flex-end', padding: 10 },
  paywallTitle: { fontSize: 32, fontWeight: '900', marginTop: 20, marginBottom: 10 },
  planCard: { width: '100%', padding: 25, borderRadius: 20, backgroundColor: '#F9F9F9', marginVertical: 10 },
  planName: { fontSize: 20, fontWeight: 'bold' },
  planPrice: { fontSize: 28, fontWeight: '900', marginVertical: 10 },
  payBtn: { backgroundColor: '#4CAF50', padding: 15, borderRadius: 12, alignItems: 'center', marginTop: 15 },
  bestValueTag: { position: 'absolute', top: -10, right: 20, backgroundColor: '#4CAF50', padding: 5, paddingHorizontal: 10, borderRadius: 10 },
});